# EDA On Google Playstore Dataset

---
1. Data Cleaning
2. EDA
3. Feature Engineering
---

# 1. Data Cleaning

In [39]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

warnings.filterwarnings("ignore")
%matplotlib inline

df = pd.read_csv('googleplaystore.csv')
df_copy = df.copy()

---
#### Operations On Column: 'Reviews'

In [40]:
# df.shape
df_copy['Reviews'].str.isnumeric().sum()
df_copy[~df['Reviews'].str.isnumeric()]
df_copy = df_copy.drop(df_copy.index[10472])
df_copy[~df['Reviews'].str.isnumeric()]

df_copy['Reviews'].astype(int)

0           159
1           967
2         87510
3        215644
4           967
          ...
10836        38
10837         4
10838         3
10839       114
10840    398307
Name: Reviews, Length: 10840, dtype: int64

---
#### Operations On Column: 'Size'

In [41]:
df_copy['Size'].isnull().sum()
df_copy['Size'] = df_copy['Size'].str.replace('M','000')
df_copy['Size'] = df_copy['Size'].str.replace('k','')
df_copy['Size'] = df_copy['Size'].replace('Varies with device',np.nan)
df_copy['Size'] = df_copy['Size'].astype(float)
df_copy['Size']

0        19000.0
1        14000.0
2            8.7
3        25000.0
4            2.8
          ...
10836    53000.0
10837        3.6
10838        9.5
10839        NaN
10840    19000.0
Name: Size, Length: 10840, dtype: float64

---
#### Operations On Column: 'Installs' And 'Price'

In [46]:
chars_to_remove = ['+','$',',']
cols_to_clean = ['Installs', 'Price']

for item in chars_to_remove:
    for cols in cols_to_clean:
        df_copy[cols] = df_copy[cols].str.replace(item,'')

df_copy['Installs'] = df_copy['Installs'].astype(int)
df_copy['Price'] = df_copy['Price'].astype(float)

---
#### Operations On Column: 'Type'

In [ ]:
df_copy['Type'] = df_copy['Type'].map({'Free':0, 'Paid':1, np.nan:0})
df_copy['Type'].unique()

0        0
1        0
2        0
3        0
4        0
        ..
10836    0
10837    0
10838    0
10839    0
10840    0
Name: Type, Length: 10840, dtype: int64

---
#### Operations On Column: 'Last Updated'

In [58]:
df_copy['Last Updated'] = pd.to_datetime(df_copy['Last Updated'])
df_copy['Date'] = df_copy['Last Updated'].dt.day
df_copy['Month'] = df_copy['Last Updated'].dt.month
df_copy['Year'] = df_copy['Last Updated'].dt.year

In [59]:
df_copy.head(3)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Date,Month,Year
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19000.0,10000,0,0.0,Everyone,Art & Design,2018-01-07,1.0.0,4.0.3 and up,7,1,2018
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14000.0,500000,0,0.0,Everyone,Art & Design;Pretend Play,2018-01-15,2.0.0,4.0.3 and up,15,1,2018
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7,5000000,0,0.0,Everyone,Art & Design,2018-08-01,1.2.4,4.0.3 and up,1,8,2018

---
# Saving File

In [87]:
df_copy.to_csv('04-googleplaystore-cleaned-data.csv', index=False)

---
# 2. EDA

---

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

warnings.filterwarnings("ignore")
%matplotlib inline

df = pd.read_csv('04-googleplaystore-cleaned-data.csv')
df_copy = df

---
#### Removing Duplicate

In [2]:
df_copy[df_copy.duplicated('App')].shape
df_copy = df_copy.drop_duplicates(subset=['App'], keep='first')

---
#### Exploring Data

In [3]:
numeric_features = [feature for feature in df_copy.columns if df_copy[feature].dtype != 'O']
categorical_features = [feature for feature in df_copy.columns if df_copy[feature].dtype == 'O']

print('We have {} numerical features: {}'.format(len(numeric_features), numeric_features))
print('We have {} Categorical features: {}'.format(len(categorical_features), categorical_features))

We have 10 numerical features: ['Unnamed: 0', 'Rating', 'Reviews', 'Size', 'Installs', 'Type', 'Price', 'Date', 'Month', 'Year']
We have 7 Categorical features: ['App', 'Category', 'Content Rating', 'Genres', 'Last Updated', 'Current Ver', 'Android Ver']

In [5]:
# df.drop('Unnamed: 0', axis=1, inplace=True)
df_copy.drop('Unnamed: 0', axis=1, inplace=True)
df_copy.head(3)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Date,Month,Year
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19000.0,10000,0,0.0,Everyone,Art & Design,2018-01-07,1.0.0,4.0.3 and up,7,1,2018
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14000.0,500000,0,0.0,Everyone,Art & Design;Pretend Play,2018-01-15,2.0.0,4.0.3 and up,15,1,2018
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7,5000000,0,0.0,Everyone,Art & Design,2018-08-01,1.2.4,4.0.3 and up,1,8,2018