# df Manipulation and Analysis with Panda

---

In [5]:
import pandas as pd

In [21]:
# Some Display operations
 
df = pd.read_csv('missing-data.csv')

df.head(5)
df.tail(5)
df.describe()  # Statistical Analysis
df.dtypes

Name       object
Age       float64
City       object
Score     float64
Salary    float64
dtype: object

#### Handling Missing Values 
---

In [ ]:
# Viewing Missing val fields

df.isnull()               # True shows Nan present
df.isnull().sum()         # |missing val per column|
df.isnull().any()         # True which column inludes missing val
df.isnull().any(axis=1)   # returns for every row

0     False
1     False
2      True
3     False
4      True
5     False
6     False
7     False
8     False
9     False
10     True
11    False
12     True
13    False
14    False
15    False
16     True
17     True
18    False
19     True
20     True
21    False
22     True
23    False
24     True
25     True
26    False
27     True
28     True
29     True
30    False
31     True
32    False
33    False
34     True
35     True
36     True
37     True
38    False
39     True
40     True
41     True
42    False
43    False
44    False
45    False
46    False
47    False
48     True
49     True
dtype: bool

In [ ]:
# Replacing all Nan with 0

df_filled = df.fillna(0)

In [ ]:
# Filling missing values with mean of its column

df['Score_fillNA'] = df['Score'].fillna(df['Score'].mean())
df

      Name   Age     City  Score   Salary  Score_fillNA
0    User1  21.0    Delhi   70.0  30000.0     70.000000
1    User2  22.0    Delhi   50.0  30000.0     50.000000
2    User3  20.0  Lucknow   70.0      NaN     70.000000
3    User4  22.0    Delhi   90.0  20000.0     90.000000
4    User5  22.0      NaN   60.0      NaN     60.000000
5    User6  19.0    Delhi   60.0  50000.0     60.000000
6    User7  20.0  Kolkata   50.0  50000.0     50.000000
7    User8  20.0  Kolkata   80.0  50000.0     80.000000
8    User9  20.0  Kolkata   50.0  50000.0     50.000000
9   User10  22.0  Kolkata   80.0  50000.0     80.000000
10  User11  21.0      NaN   60.0  40000.0     60.000000
11  User12  20.0   Mumbai   50.0  30000.0     50.000000
12  User13   NaN  Lucknow    NaN  50000.0     71.363636
13  User14  22.0  Kolkata   90.0  20000.0     90.000000
14  User15  19.0    Delhi   70.0  20000.0     70.000000
15  User16  21.0  Kolkata   80.0  20000.0     80.000000
16  User17   NaN    Delhi    NaN  20000.0     71.363636
17  User18   NaN    Delhi   70.0  40000.0     70.000000
18  User19  19.0  Kolkata   70.0  20000.0     70.000000
19  User20  21.0      NaN   50.0  50000.0     50.000000
20  User21  22.0    Delhi   70.0      NaN     70.000000
21  User22  18.0    Delhi   90.0  20000.0     90.000000
22  User23  21.0  Kolkata    NaN  40000.0     71.363636
23  User24  19.0    Delhi   70.0  40000.0     70.000000
24  User25   NaN    Delhi   50.0  20000.0     50.000000
25  User26  22.0  Kolkata   90.0      NaN     90.000000
26  User27  21.0  Kolkata   60.0  20000.0     60.000000
27  User28  18.0  Lucknow    NaN  40000.0     71.363636
28  User29  18.0      NaN   70.0  30000.0     70.000000
29  User30  20.0      NaN   50.0  50000.0     50.000000
30  User31  20.0    Delhi   60.0  40000.0     60.000000
31  User32  19.0      NaN   60.0  20000.0     60.000000
32  User33  21.0    Delhi   80.0  50000.0     80.000000
33  User34  21.0  Lucknow   90.0  20000.0     90.000000
34  User35   NaN  Kolkata   70.0  20000.0     70.000000
35  User36   NaN  Kolkata   50.0  30000.0     50.000000
36  User37   NaN  Kolkata   80.0  50000.0     80.000000
37  User38  20.0      NaN   90.0  50000.0     90.000000
38  User39  21.0  Lucknow   80.0  30000.0     80.000000
39  User40  21.0      NaN    NaN  40000.0     71.363636
40  User41  18.0      NaN   90.0  20000.0     90.000000
41  User42  20.0  Lucknow   90.0      NaN     90.000000
42  User43  22.0  Lucknow   70.0  20000.0     70.000000
43  User44  20.0  Lucknow   90.0  20000.0     90.000000
44  User45  22.0  Lucknow   80.0  40000.0     80.000000
45  User46  18.0  Kolkata   90.0  20000.0     90.000000
46  User47  19.0   Mumbai   70.0  30000.0     70.000000
47  User48  21.0   Mumbai   70.0  30000.0     70.000000
48  User49  18.0  Lucknow    NaN  50000.0     71.363636
49  User50  21.0   Mumbai   80.0      NaN     80.000000

#### Renaming, Changing Datatypes & Apply functions

---

In [ ]:
# Renaming Column

df = df.rename(columns={'Score_fillNA':'Score-FILLED'})

In [28]:
# df.dtypes
df['Score-FILLED-INT'] = df['Score-FILLED'].astype(int)

In [36]:
# Using function

df['fill_Salary'] = df['Salary'].fillna(df['Salary'].mean())
df['fill_Salary'] = df['fill_Salary'].apply(lambda x:x+2000)
df['fill_Salary'] = df['fill_Salary'].astype(int)
df.head()

,Name,Age,City,Score,Salary,Score-FILLED,Score-FILLED-INT,fill_Salary
0,User1,21.0,Delhi,70.0,30000.0,70.0,70,32000
1,User2,22.0,Delhi,50.0,30000.0,50.0,50,32000
2,User3,20.0,Lucknow,70.0,NaN,70.0,70,35636
3,User4,22.0,Delhi,90.0,20000.0,90.0,90,22000
4,User5,22.0,NaN,60.0,NaN,60.0,60,35636

#### Data Aggregating and Grouping
---

In [40]:
# Group based on Single column City and calc mean of thier Score

grouped_mean = df.groupby('City')['Score'].mean()
print(grouped_mean)

City
Delhi      69.166667
Kolkata    72.307692
Lucknow    81.428571
Mumbai     67.500000
Name: Score, dtype: float64

In [42]:
# Group based on two column

grouped_sum = df.groupby(['City', 'Age'])['Score'].sum()
print(grouped_sum)

City     Age
Delhi    18.0     90.0
         19.0    200.0
         20.0     60.0
         21.0    150.0
         22.0    210.0
Kolkata  18.0     90.0
         19.0     70.0
         20.0    180.0
         21.0    140.0
         22.0    260.0
Lucknow  18.0      0.0
         20.0    250.0
         21.0    170.0
         22.0    150.0
Mumbai   19.0     70.0
         20.0     50.0
         21.0    150.0
Name: Score, dtype: float64

In [43]:
# Multiple Aggregate Function Applied

grouped_agg = df.groupby(['Age','City'])['Score'].agg(['mean', 'count', 'sum'])
print(grouped_agg)

                   mean  count    sum
Age  City
18.0 Delhi    90.000000      1   90.0
     Kolkata  90.000000      1   90.0
     Lucknow        NaN      0    0.0
19.0 Delhi    66.666667      3  200.0
     Kolkata  70.000000      1   70.0
     Mumbai   70.000000      1   70.0
20.0 Delhi    60.000000      1   60.0
     Kolkata  60.000000      3  180.0
     Lucknow  83.333333      3  250.0
     Mumbai   50.000000      1   50.0
21.0 Delhi    75.000000      2  150.0
     Kolkata  70.000000      2  140.0
     Lucknow  85.000000      2  170.0
     Mumbai   75.000000      2  150.0
22.0 Delhi    70.000000      3  210.0
     Kolkata  86.666667      3  260.0
     Lucknow  75.000000      2  150.0